Repository leoelicos/just-kidding, pull requests merged in 2022-06, with the labels that each got.

#84 fixing eslint
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  public/js/login.js
Labels: admin

#86 homepage handlebars Created
  views/homepage.handlebars
Labels: View

#87 Create readme
  LICENSE
  README.md
Labels: documentation

#85 login handlebars fixed
  views/login.handlebars
Labels: View

#88 added baby and css to main handlebar and normalize
  index.html
  public/css/normalize.css
  public/css/style.css
  public/images/happy-baby.png
  views/layouts/main.handlebars
Labels: View

#89 updated pckage json with multer
  package-lock.json
  package.json
Labels: Controller, admin

#90 integration part one
  .DS_Store
  controllers/api/userRoutes.js
  models/Thread.js
  public/.DS_Store
  public/css/style.css
  public/images/.DS_Store
  public/images/angry-baby.jpg
  public/images/babyStuff.png
  public/images/babySurprise.jpg
  public/js/login.js
  seeds/thread-seeds.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
Labels: admin

#95 Leo feature marketplace picture
  public/images/baby-items.png
  public/images/babyIcon.jpg
  seeds/thread-seeds.js
  views/layouts/main.handlebars
Labels: View

#108 Add seeds, reject post submit if any inputs are empty
  controllers/api/postRoutes.js
  public/data/uploads/1654564969248.jpeg
  public/data/uploads/1654565367966.jpg
  public/data/uploads/1654565488313.jpg
  public/data/uploads/1654565527867.jpeg
  public/images/BabyStuff.jpg
  public/images/cryingbaby.png
  public/images/seeds/angrybaby.jpg
  public/images/seeds/angrykid.jpg
  public/images/seeds/babybottles.jpg
  public/images/seeds/babynappies.jpg
  public/images/seeds/balancebike.jpg
  public/images/seeds/candy.jpg
  public/images/seeds/confessionangry.jpeg
  public/images/seeds/cryingbaby.jpg
  public/images/seeds/pram.jpg
  public/images/seeds/pretendsleep.jpg
  seeds/post-seeds.js
  views/thread.handlebars
Labels: View, Controller

#109 Title Changed
  README.md
Labels: admin

#110 main hadlebar comment fixed
  views/layouts/main.handlebars
Labels: admin
