Repository leoelicos/just-kidding, pull requests merged in 2022-05, with the labels that each got.

#41 Admin 24 package json
  .gitignore
  package-lock.json
  package.json
Labels: documentation

#42 eslintrc json created
  .eslintrc.json
Labels: documentation

#43 eslintignore create
  .eslintignore
Labels: documentation

#45 added blank files for base structure
  .env.EXAMPLE
  config/connection.js
  controllers/api/index.js
  controllers/api/postRoutes.js
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  controllers/index.js
  db/schema.sql
  models/Post.js
  models/Thread.js
  models/User.js
  models/index.js
  package.json
  public/css/style.css
  public/js/login.js
  public/js/logout.js
  public/js/post.js
  seeds/index.js
  seeds/post-seeds.js
  seeds/thread-seeds.js
  seeds/user-seeds.js
  server.js
  utils/auth.js
  utils/helpers.js
  views/homepage.handlebars
  views/layouts/main.handlebars
  views/login.handlebars
  views/partials/history.handlebars
  views/thread.handlebars
Labels: documentation

#49 created user seed
  .env
  seeds/user-seeds.js
Labels: documentation

#47 Jess 31 conection.js
  .gitignore
  config/connection.js
  package-lock.json
Labels: View

#48 Implement Post Model
  models/Post.js
Labels: View

#50 Thread model created
  models/Thread.js
Labels: View

#53 Add some seeds for Post
  seeds/post-seeds.js
Labels: Model

#55 thread seed created & checked with lint
  models/Thread.js
  seeds/thread-seeds.js
Labels: Model

#57 Delete .env
  .env
Labels: admin

#56 updating user model
  models/User.js
Labels: Model

#54 making index file for models connection
  models/index.js
Labels: Model

#52 updated user seeds
  seeds/user-seeds.js
Labels: Model

#58 link thread-seeds, user-seeds, post-seeds
  seeds/index.js
Labels: Model

#60 Change order of seeding - move seedPosts last
  seeds/index.js
Labels: Model

#61 adding index.js for connecting api routes
  controllers/index.js
Labels: Controller

#62 Implement server.js
  server.js
Labels: Controller

#63 Implement postRoutes and userRoutes
  controllers/api/index.js
Labels: Controller

#64 adding util auth
  utils/auth.js
Labels: Controller

#73 cleaned up eslint fixes
  controllers/api/userRoutes.js
  controllers/homeRoutes.js
  seeds/user-seeds.js
  utils/helpers.js
Labels: admin
